stages:
  data_ingestion:
    cmd: python src/data/make_dataset.py
    deps:
    - src/data/make_dataset.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/features/build_features.py
    deps:
    - data/processed
    - src/features/build_features.py
    outs:
    - data/features
  model_building:
    cmd: python src/models/train_model.py
    deps:
    - data/features
    - src/models/train_model.py
    outs:
    - model.pkl
  model_evaluation:
    cmd: python src/models/predict_model.py
    deps:
    - data/features
    - src/models/predict_model.py
    outs:
    - metrics.json
